# -*- coding: utf-8 -*-
"""delivery.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d3Y4aSLl-3_K1Zv3WY9XlHvta0MUdBuI
"""

class DeliveryApp:
    def __init__(self, server, payment_gateway):
        self.server = server
        self.payment_gateway = payment_gateway

    def place_order(self, item):
        print(f"[App] '{item}' 주문 요청")
        result = self.server.receive_order(item)
        print(f"[App] 서버 응답: {result}")
        return result

    def make_payment(self, amount):
        print(f"[App] {amount}원 결제 요청")
        success = self.payment_gateway.process(amount)
        if success:
            print("[App] 결제 성공")
            self.server.notify_payment()
        else:
            print("[App] 결제 실패")

    def check_delivery_status(self):
        status = self.server.get_delivery_status()
        print(f"[App] 배달 상태: {status}")

class Server:
    def __init__(self, delivery_service):
        self.delivery_service = delivery_service
        self.delivery_started = False

    def receive_order(self, item):
        print(f"[Server] 주문 '{item}' 접수")
        return "주문 확인"

    def notify_payment(self):
        print("[Server] 결제 완료 확인")
        self.delivery_started = self.delivery_service.start_delivery()

    def get_delivery_status(self):
        return "배달 중" if self.delivery_started else "대기 중"

class PaymentGateway:
    def process(self, amount):
        print(f"[PaymentGateway] {amount}원 결제 처리 중...")
        return True

class DeliveryService:
    def start_delivery(self):
        print("[DeliveryService] 배달 시작")
        return True

# 시뮬레이션 실행
delivery_service = DeliveryService()
server = Server(delivery_service)
payment_gateway = PaymentGateway()
app = DeliveryApp(server, payment_gateway)

# 시나리오 진행
app.place_order("불고기 피자")
app.make_payment(18000)
app.check_delivery_status()

